# Generated by Django 3.2.4 on 2021-06-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
    ]
