# Generated by Django 3.2.4 on 2021-06-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupoCero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('historia', models.TextField()),
                ('descripcion', models.TextField()),
                ('tecnica', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupoCero.categoria')),
            ],
        ),
    ]
