# Generated by Django 3.2.4 on 2021-07-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoCero', '0003_alter_obra_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
