# Generated by Django 3.2.4 on 2021-07-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoCero', '0008_obra_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='artista',
            field=models.CharField(default='--', max_length=60, null=True),
        ),
    ]
