# Generated by Django 3.2.4 on 2021-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoCero', '0009_alter_obra_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(default='fotos/no_disponible.jpg', upload_to='fotos'),
        ),
    ]
