# Generated by Django 3.2.4 on 2021-07-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupoCero', '0010_alter_obra_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupoCero.obra')),
            ],
        ),
    ]
