# Generated by Django 3.2.4 on 2021-07-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupoCero', '0011_galeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='mascota',
            new_name='obra',
        ),
    ]
