# Generated by Django 3.2.4 on 2021-07-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoCero', '0012_rename_mascota_galeria_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('mensaje', models.TextField(default='--')),
            ],
        ),
    ]
